-- Asta Fantacalcio — schema isolato nel progetto "Content Breakdown"
-- Eseguire in Supabase → SQL Editor.

create schema if not exists fanta;

create table if not exists fanta.auctions (
  id          uuid primary key default gen_random_uuid(),
  name        text not null default 'Asta 2026/27',
  budget      integer not null default 750 check (budget >= 0),
  roster      jsonb not null default '{"P":3,"D":10,"C":10,"A":7}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists fanta.teams (
  id          uuid primary key default gen_random_uuid(),
  auction_id  uuid not null references fanta.auctions(id) on delete cascade,
  slot        smallint not null check (slot >= 0),
  name        text not null,
  unique (auction_id, slot)
);

create table if not exists fanta.players (
  id          uuid primary key default gen_random_uuid(),
  auction_id  uuid not null references fanta.auctions(id) on delete cascade,
  name        text not null,
  role        text not null check (role in ('P','D','C','A')),
  team        text,
  price       integer
);
create unique index if not exists players_unique_name_role
  on fanta.players (auction_id, lower(name), role);
create index if not exists players_auction_idx on fanta.players (auction_id);

create table if not exists fanta.assignments (
  id          uuid primary key default gen_random_uuid(),
  auction_id  uuid not null references fanta.auctions(id) on delete cascade,
  team_id     uuid not null references fanta.teams(id) on delete cascade,
  player_name text not null,
  role        text not null check (role in ('P','D','C','A')),
  price       integer not null check (price >= 0),
  seq         bigint generated by default as identity,
  created_at  timestamptz not null default now()
);
-- impedisce che lo stesso giocatore venga venduto due volte nella stessa asta
create unique index if not exists assignments_unique_player
  on fanta.assignments (auction_id, lower(player_name), role);
create index if not exists assignments_auction_seq_idx
  on fanta.assignments (auction_id, seq);

alter table fanta.auctions    enable row level security;
alter table fanta.teams       enable row level security;
alter table fanta.players     enable row level security;
alter table fanta.assignments enable row level security;

-- ATTENZIONE: l'app non ha login, quindi le policy sono aperte al ruolo anon.
-- Chiunque abbia URL + anon key puo' leggere e scrivere SOLO lo schema fanta.
do $$
declare t text;
begin
  foreach t in array array['auctions','teams','players','assignments'] loop
    execute format('drop policy if exists anon_all on fanta.%I', t);
    execute format(
      'create policy anon_all on fanta.%I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;

grant usage on schema fanta to anon, authenticated;
grant all on all tables in schema fanta to anon, authenticated;
grant all on all sequences in schema fanta to anon, authenticated;
alter default privileges in schema fanta grant all on tables to anon, authenticated;
alter default privileges in schema fanta grant all on sequences to anon, authenticated;

-- realtime: aggiorna gli altri dispositivi in diretta
alter publication supabase_realtime add table fanta.auctions;
alter publication supabase_realtime add table fanta.teams;
alter publication supabase_realtime add table fanta.assignments;
